// src/app/cabine/cabine.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'cabine',
  templateUrl: './cabine.component.html',
  styleUrls: ['./cabine.component.css']
})
export class CabineComponent {

  constructor() {
    this.options = [];
  }

  @Input() options: any[];
  @Output() vote:EventEmitter<number> = new EventEmitter<number>();

}

<button
    class="m5"
    *ngFor="let option of options; index as i"
    (click)="vote.emit(i)"
>
    {{ option.opcao }}
</button>

// src/components/Cabine.vue
<template>
  <div>
    <h1>{{ statement }}</h1>
    <button
      v-for="(option, index) in options"
      class="m5"
      :class="{ selected: index == selection }"
      :key="option"
      @click="$emit('vote', index)"
    >{{ option.opcao }}</button>
  </div>
</template>

<script>
export default {
  props: ['options']
}
</script>

<style>
.selected {
  font-weight: bold;
}
</style>
