// src/Cabine.svelte
{#each options as option, index (option)}
<button class="m5" class:selected="{index===selection}" on:click={dispatch('selected', index)}>{option}
</button>
{/each}

<script>
	export let options
	export let selection
	import { createEventDispatcher } from 'svelte'

	const dispatch = createEventDispatcher()
</script>

<style>
  .selected {
    font-weight: bold;
  }
</style>

// src/components/Cabine.vue
<template>
  <div>
    <h1>{{ statement }}</h1>
    <button
      v-for="(option, index) in options"
      class="m5"
      :class="{ selected: index == selection }"
      :key="option"
      @click="$emit('vote', index)"
    >{{ option.opcao }}</button>
  </div>
</template>

<script>
export default {
  props: ['options']
}
</script>

<style>
.selected {
  font-weight: bold;
}
</style>
