// src/components/Card.vue
<template>
  <div>
    <div v-if="mode === 'questions'">
      <div class="panel question">
        <p class="m5">{{statement}}</p>
        <Cabine
          :options="options"
          @vote="vote"
        />
      </div>
    </div>
    <div v-else>
      <div class="panel results">
        <Resultado 
        :options="options" />
      </div>
    </div>
  </div>
</template>

<script>
import Cabine from './Cabine'
import Resultado from './Resultado'

const options= [
    {
        count: 0,
        opcao: 'time X'
    },
    {
        count: 0,
        opcao: 'time Y'
    },
    {
        count: 0,
        opcao: 'time Z'
    }
  ]

export default {
  props: ['statement'],
  components: { Cabine, Resultado },
  data: () => ({
    mode: 'questions'
  }),
  methods: {
    vote(index){ // capturando o voto do usuário
        console.log("frase só pra ver se eu to chegando aqui");
        this.options[index].count = this.options[index].count + 1;
        this.mode = 'result';
    }
  },
  computed: {
    options(){
        return options
    },
    option(){
        return options[this.index];
    }
  }
}
</script>


<style>
.panel {
  padding: 10px;
  border-radius: 5px;
  border: 1px solid #ddd;
}
.question {
  background-color: azure;
}
.results {
  background-color: beige;
}
.m5 {
  margin: 5px;
}
.submitBtn {
  margin: 15px;
}
</style>

// src/Card.svelte
{#if mode === 'open'}
<div class="panel question">
	<p class="m5">{statement}</p>
	<Cabine {options} on:selected={vote} />
</div>
<!-- <button class="submitBtn" on:click={next}>Próxima questão</button> -->

{:else}
<div class="panel results">
	<Resultado {options} />
</div>
{/if}


<script>
  import Cabine from './Cabine.svelte'
  import Resultado from './Resultado.svelte'

  
  let mode = 'open'
  export let statement
  export let options
//   $: statement = `Questão ${current + 1}: ${questions[current].statement}`
//   $: options = questions[current].options

  function vote(event){
    mode = 'closed';
    // alert(event.detail);
    options[event.detail].count = options[event.detail].count + 1;
  }
</script>

<style>
  .panel {
    padding: 10px;
    border-radius: 5px;
    border: 1px solid #ddd;
  }
  .question {
    background-color: azure;
  }
  .results {
    background-color: beige;
  }
  :global(.m5) {
    margin: 5px;
  }
</style>
