// src/app/card/card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'card',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.css']
})
export class CardComponent {

  constructor(){
    this.statement = '';
    this.options = [];
    this.mode = 'open';
  }
  mode = 'open';
  @Input() statement: string
  @Input() options: any[]

  vote(i: number){
    console.log("entrei aqui");
    this.options[i].count = this.options[i].count + 1;
    this.mode = 'closed';
  }

}

<div *ngIf="mode === 'open'; else closed">
  <div class="panel question">
    <p class="m5">{{ statement }}</p>
    <cabine
      [options]="options"
      (vote)="vote($event)"
    >
    </cabine>
  </div>
</div>
<ng-template #closed>
  <div class="panel results">
    <resultado 
    [options]="options"></resultado>
  </div>
</ng-template>

// src/Card.svelte
{#if mode === 'open'}
<div class="panel question">
	<p class="m5">{statement}</p>
	<Cabine {options} on:selected={vote} />
</div>
<!-- <button class="submitBtn" on:click={next}>Próxima questão</button> -->

{:else}
<div class="panel results">
	<Resultado {options} />
</div>
{/if}


<script>
  import Cabine from './Cabine.svelte'
  import Resultado from './Resultado.svelte'

  
  let mode = 'open'
  export let statement
  export let options
//   $: statement = `Questão ${current + 1}: ${questions[current].statement}`
//   $: options = questions[current].options

  function vote(event){
    mode = 'closed';
    // alert(event.detail);
    options[event.detail].count = options[event.detail].count + 1;
  }
</script>

<style>
  .panel {
    padding: 10px;
    border-radius: 5px;
    border: 1px solid #ddd;
  }
  .question {
    background-color: azure;
  }
  .results {
    background-color: beige;
  }
  :global(.m5) {
    margin: 5px;
  }
</style>
